# Generated by Django 6.0.2 on 2026-02-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("status", models.CharField(default="new", max_length=32)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("label_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_id", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "abstract": False,
                "swappable": "SENDPARCEL_DJANGO_SHIPMENT_MODEL",
            },
        ),
    ]
