# Generated by Django 6.0.2 on 2026-02-16 03:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendparcel_django", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallbackRetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.CharField(db_index=True, max_length=128)),
                ("payload", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                ("attempts", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
