# Generated by Django 6.0.2 on 2026-02-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sendparcel_django", "0002_callbackretry"),
    ]

    operations = [
        migrations.AddField(
            model_name="callbackretry",
            name="provider_slug",
            field=models.CharField(default="unknown", max_length=64),
        ),
    ]
