# Generated by Django 6.0.2 on 2026-03-20 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sendparcel_django", "0003_callbackretry_provider_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="label_url",
        ),
        migrations.AlterField(
            model_name="callbackretry",
            name="attempts",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
