# ruff: noqa
# Generated by Django 6.0.5 on 2026-05-29 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendparcel_django", "0004_remove_shipment_label_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookDedup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload_hash", models.CharField(db_index=True, max_length=64)),
                ("shipment_id", models.CharField(db_index=True, max_length=128)),
                ("provider_slug", models.CharField(default="unknown", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
