# Generated by Django 6.0.5 on 2026-05-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendparcel_django", "0005_webhook_dedup"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="webhookdedup",
            constraint=models.UniqueConstraint(
                fields=("shipment_id", "payload_hash"),
                name="sendparcel_django_webhookdedup_shipment_hash_unique",
            ),
        ),
    ]
