# Generated by Django 6.0.5 on 2026-06-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sendparcel_django",
            "0006_webhookdedup_sendparcel_django_webhookdedup_shipment_hash_unique",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="callbackretry",
            name="raw_body",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callbackretry",
            name="source_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
