# Generated by Django 6.0.5 on 2026-07-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sendparcel_django", "0007_callbackretry_add_source_ip_and_raw_body"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference_id", ""), _negated=True),
                fields=("provider", "reference_id"),
                name="sendparcel_django_shipment_provider_reference_unique",
            ),
        ),
    ]
