# Generated by Django 6.0.2 on 2026-02-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("status", models.CharField(default="new", max_length=32)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("label_url", models.URLField(blank=True, default="")),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=(
                            "External reference identifier"
                            " (e.g. order ID, return ID)"
                        ),
                        max_length=255,
                        verbose_name="Reference ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sender_name",
                    models.CharField(
                        default="Example Warehouse",
                        max_length=128,
                        verbose_name="sender name",
                    ),
                ),
                (
                    "sender_street",
                    models.CharField(
                        default="1 Warehouse St",
                        max_length=255,
                        verbose_name="sender street",
                    ),
                ),
                (
                    "sender_city",
                    models.CharField(
                        default="Warsaw",
                        max_length=128,
                        verbose_name="sender city",
                    ),
                ),
                (
                    "sender_postal_code",
                    models.CharField(
                        default="00-001",
                        max_length=16,
                        verbose_name="sender postal code",
                    ),
                ),
                (
                    "sender_country_code",
                    models.CharField(
                        default="PL",
                        max_length=2,
                        verbose_name="sender country code",
                    ),
                ),
                (
                    "receiver_name",
                    models.CharField(
                        max_length=128, verbose_name="receiver name"
                    ),
                ),
                (
                    "receiver_street",
                    models.CharField(
                        max_length=255, verbose_name="receiver street"
                    ),
                ),
                (
                    "receiver_city",
                    models.CharField(
                        max_length=128, verbose_name="receiver city"
                    ),
                ),
                (
                    "receiver_postal_code",
                    models.CharField(
                        max_length=16, verbose_name="receiver postal code"
                    ),
                ),
                (
                    "receiver_country_code",
                    models.CharField(
                        default="PL",
                        max_length=2,
                        verbose_name="receiver country code",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        verbose_name="weight (kg)",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=10, verbose_name="width (cm)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=10, verbose_name="height (cm)"
                    ),
                ),
                (
                    "length",
                    models.PositiveIntegerField(
                        default=10, verbose_name="length (cm)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
                "ordering": ["-created_at"],
            },
        ),
    ]
