# Generated by Django 6.0.2 on 2026-02-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="opis")),
                (
                    "package_size",
                    models.CharField(
                        choices=[
                            ("S", "Mały (do 1 kg)"),
                            ("M", "Średni (do 5 kg)"),
                            ("L", "Duży (do 15 kg)"),
                        ],
                        default="M",
                        max_length=2,
                        verbose_name="rozmiar paczki",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        default="Przykładowy Magazyn",
                        max_length=128,
                        verbose_name="nazwa nadawcy",
                    ),
                ),
                (
                    "sender_line1",
                    models.CharField(
                        default="ul. Magazynowa 1",
                        max_length=255,
                        verbose_name="adres nadawcy",
                    ),
                ),
                (
                    "sender_city",
                    models.CharField(
                        default="Warszawa",
                        max_length=128,
                        verbose_name="miasto nadawcy",
                    ),
                ),
                (
                    "sender_postal_code",
                    models.CharField(
                        default="00-001",
                        max_length=16,
                        verbose_name="kod pocztowy nadawcy",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=128, verbose_name="nazwa odbiorcy"),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="e-mail odbiorcy"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=32, verbose_name="telefon odbiorcy"),
                ),
                (
                    "recipient_line1",
                    models.CharField(max_length=255, verbose_name="adres odbiorcy"),
                ),
                (
                    "recipient_city",
                    models.CharField(max_length=128, verbose_name="miasto odbiorcy"),
                ),
                (
                    "recipient_postal_code",
                    models.CharField(
                        max_length=16, verbose_name="kod pocztowy odbiorcy"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
                ),
            ],
            options={
                "verbose_name": "zamówienie",
                "verbose_name_plural": "zamówienia",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("status", models.CharField(default="new", max_length=32)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("label_url", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="utworzono"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="shipping.order",
                        verbose_name="zamówienie",
                    ),
                ),
            ],
            options={
                "verbose_name": "przesyłka",
                "verbose_name_plural": "przesyłki",
                "ordering": ["-created_at"],
            },
        ),
    ]
