# Generated by Django 6.0.2 on 2026-02-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "package_size",
                    models.CharField(
                        choices=[
                            ("S", "Small (up to 1 kg)"),
                            ("M", "Medium (up to 5 kg)"),
                            ("L", "Large (up to 15 kg)"),
                        ],
                        default="M",
                        max_length=2,
                        verbose_name="package size",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(
                        default="Example Warehouse",
                        max_length=128,
                        verbose_name="sender name",
                    ),
                ),
                (
                    "sender_line1",
                    models.CharField(
                        default="1 Warehouse St",
                        max_length=255,
                        verbose_name="sender address",
                    ),
                ),
                (
                    "sender_city",
                    models.CharField(
                        default="Warsaw",
                        max_length=128,
                        verbose_name="sender city",
                    ),
                ),
                (
                    "sender_postal_code",
                    models.CharField(
                        default="00-001",
                        max_length=16,
                        verbose_name="sender postal code",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=128, verbose_name="recipient name"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        max_length=254, verbose_name="recipient email"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        max_length=32, verbose_name="recipient phone"
                    ),
                ),
                (
                    "recipient_line1",
                    models.CharField(
                        max_length=255, verbose_name="recipient address"
                    ),
                ),
                (
                    "recipient_city",
                    models.CharField(
                        max_length=128, verbose_name="recipient city"
                    ),
                ),
                (
                    "recipient_postal_code",
                    models.CharField(
                        max_length=16, verbose_name="recipient postal code"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("status", models.CharField(default="new", max_length=32)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("label_url", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created at"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="shipping.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipment",
                "verbose_name_plural": "shipments",
                "ordering": ["-created_at"],
            },
        ),
    ]
