# Generated by Django 6.0.2 on 2026-03-20 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="label_url",
        ),
    ]
